# Generated by Django 5.2.3 on 2025-06-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppings',
            old_name='topping',
            new_name='pizza',
        ),
    ]
