# Generated by Django 5.2.3 on 2025-06-23 09:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_rename_topping_toppings_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='text',
        ),
        migrations.AddField(
            model_name='pizza',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True, default='No description provided.'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=199.99, max_digits=5),
        ),
        migrations.AddField(
            model_name='toppings',
            name='is_spicy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toppings',
            name='name',
            field=models.CharField(default='Cheese', max_length=100),
        ),
        migrations.AddField(
            model_name='toppings',
            name='quantity',
            field=models.CharField(default='50g', help_text='e.g., 2 slices, 50g, 1 tbsp', max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='Custom Pizza', max_length=200),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pizzas.pizza'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('comment', models.TextField(blank=True, default='No comment.')),
                ('rated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pizza', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pizzas.pizza')),
            ],
        ),
    ]
