# Generated by Django 5.2.3 on 2025-06-27 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_remove_toppings_text_pizza_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pizzas.pizza'),
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cheese', max_length=100)),
                ('quantity', models.CharField(default='50g', help_text='e.g., 2 slices, 50g, 1 tbsp', max_length=50)),
                ('is_spicy', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizza')),
            ],
            options={
                'verbose_name_plural': 'Toppings',
            },
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
